name: Deploy API (Azure App Service)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'
      PUBLISH_DIR: ${{ github.workspace }}/publish
      ZIP_PATH:     ${{ github.workspace }}/app.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # --- Locate the Web API project reliably ---
      - name: Locate Api.csproj
        id: locate
        shell: bash
        run: |
          set -e
          PROJ=$(git ls-files '**/Api.csproj' | head -n1)
          if [ -z "$PROJ" ]; then
            echo "pi.csproj not found"; exit 1
          fi
          echo "PROJECT_PATH=$PROJ" >> $GITHUB_ENV
          echo "PROJECT_DIR=$(dirname "$PROJ")" >> $GITHUB_ENV
          echo "Found project at: $PROJ"

      - name: Restore
        working-directory: ${{ env.PROJECT_DIR }}
        run: dotnet restore "$(basename "${{ env.PROJECT_PATH }}")"

      - name: Build (Release)
        working-directory: ${{ env.PROJECT_DIR }}
        run: dotnet build "$(basename "${{ env.PROJECT_PATH }}")" -c Release --no-restore

     
      - name: Publish
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          rm -rf "$PUBLISH_DIR" "$ZIP_PATH"
          dotnet publish "$(basename "${{ env.PROJECT_PATH }}")" -c Release \
            -p:PublishTrimmed=false -p:PublishAot=false -p:SelfContained=false \
            -o "$PUBLISH_DIR"

          echo "Remove any backup runtimeconfig files (Azure Oryx gets confused):"
          find "$PUBLISH_DIR" -maxdepth 1 -type f -iname "*backup*.runtimeconfig.json" -print -delete || true

          echo "List publish output:"
          ls -la "$PUBLISH_DIR"

          echo "Assert exactly one runtimeconfig.json remains:"
          COUNT=$(find "$PUBLISH_DIR" -maxdepth 1 -type f -name "*.runtimeconfig.json" | wc -l)
          if [ "$COUNT" -ne 1 ]; then
            echo "Expected exactly 1 *.runtimeconfig.json, found $COUNT"; exit 1
          fi

      - name: Zip artifact
        run: |
          cd "$PUBLISH_DIR"
          zip -r "$ZIP_PATH" .
          cd -
          echo "Created: $ZIP_PATH"

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: doormeen-api   
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.ZIP_PATH }}
