name: Deploy API (Azure App Service Free)

on:
  push:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Show tree
  run: |
    pwd
    ls -la
    find . -maxdepth 3 -type f -name "*.csproj" -print

- name: Fail if no .csproj
  run: |
    PROJ=$(find . -type f -name "*.csproj" | head -n1)
    if [ -z "$PROJ" ]; then
      echo "No .csproj found. Did you commit it?"; exit 1;
    fi
    echo "PROJECT_PATH=$PROJ" >> $GITHUB_ENV



    - name: Restore
  run: dotnet restore "$PROJECT_PATH"

- name: Build
  run: dotnet build -c Release --no-restore "$PROJECT_PATH"

- name: Publish
  run: dotnet publish -c Release -o publish "$PROJECT_PATH"

- name: Deploy to Azure App Service
  uses: azure/webapps-deploy@v3
  with:
    app-name: doormeen-api
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: publish     # publish folder created in repo root by the step above
