name: Deploy API (Azure App Service Free)

on:
  push:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      

      - name: Restore
        run: dotnet restore Api/Api.csproj

      - name: Build
        run: dotnet build -c Release --no-restore Api/Api.csproj

      - name: Publish
        run: dotnet publish -c Release -o Api/publish Api/Api.csproj

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: doormeen-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Api/publish   
